### ISSUE TITLE
Limit to one polygon per point

### ISSUE THREAD

**Issue by jeroen** [mapbox/leaflet-pip#1]
Is it possible to speed up the algorithm by adding an option to assume that each point is only contained in one polygon? Hence return once a match has been found.

I need to classify a large number of points, so speed is an issue for me.

**Comment by tmcw** [comment]
Added an accept-first option (default false). It's certainly possible to write other kinds of optimizations - rasterization, web workers, and whatever, but I'm not planning on them in this project.

**Comment by jeroen** [comment]
Thanks :)
