### ISSUE TITLE
Add bower package

### ISSUE THREAD

**Issue by nikolauskrismer** [mapbox/leaflet-pip#10]
Could you please add a bower package and make it available on bower.io?
This would ease usage for many web-projects :-)

**Comment by tmcw** [comment]
Ugh, yeah... I'll run `sellout` on this when I get back home. In the meantime, I'd really recommend using `npm` and `browserify` - they offer quite significant advantages over bower.

**Comment by nikolauskrismer** [comment]
Any news on this? Would really help me (and I guess others too) a lot :)

**Comment by tmcw** [comment]
You can also just submit a PR, and it will happen as soon as I push the green button.

**Comment by tmcw** [comment]
Added it. Still have very negative feelings about supporting Bower.

**Comment by nikolauskrismer** [comment]
Helps me a lot. Thank you !! ;-)
