### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by saxicek** [mapbox/leaflet-pip#11]
Current is 0.1.0 which unfortunately does not include bower.json and Bower is then complaining about missing "main" and "ignore" entries. Since bower.json is committed in the repository already, it would be nice to release a new version to please Bower. :-)

**Comment by tmcw** [comment]
Meh. Unless people are actually actively using the bower version of this, I'm probably going to remove it: there's zero advantage to bower over npm, and the tools you use to interact with bower are buggy and unfinished. It's just not worth the time.

**Comment by saxicek** [comment]
But how do you tell whether people prefer npm over bower? I am using npm for server side, bower for client side. Not saying it is the best but I am just using it like that and it works for me.

**Comment by tmcw** [comment]
> But how do you tell whether people prefer npm over bower?

Ideally by comparing the download stats of the [npm package](https://www.npmjs.org/package/leaflet-pip) versus the bower package, but since bower doesn't do statistics, I can't.

**Comment by saxicek** [comment]
Exactly. Bower implemented anonymous statistics as opt-in feature, but because it tends to break [automation](https://github.com/bower/bower/issues/1102), not sure what data they receive.

**Comment by tmcw** [comment]
Given that amongst other [issues I've run into](https://github.com/bower/registry-client/issues/16), it feels like I should wait until things are stable. Really, browserify is a very very good thing.

**Comment by saxicek** [comment]
I am using Require.js instead because I need async support for Google Maps and Analytics. It does not seem that Browserify can help with that. And it does not help with other resources such as CSS, images either (Leaflet). But it is also possible that I am doing something terribly wrong.

**Comment by rayshan** [comment]
@tmcw stats are here: http://bower.io/stats/, what's tracked is here: https://github.com/yeoman/insight#collected-data

We're working on a per-package API so people can query stats

**Comment by tmcw** [comment]
I get that there's a 'top modules' stats page, but there isn't a page for anything beyond the top 100 packages, right?

**Comment by rayshan** [comment]
Sorry not yet. Coming soon though.

**Comment by tmcw** [comment]
Closing: feel free to maintain a third-party bower package, but it adds too much friction for too little traction to be worth it for me.
