### ISSUE TITLE
Server side

### ISSUE THREAD

**Issue by alexcroox** [mapbox/leaflet-pip#12]
I need to use this server side to give a reward, so therefore I cannot trust the client. Is there anyway of using this server side in nodejs? I notice in the source it seems to be actually drawing polygons to determine so I'm thinking not? Sorry for my ignorance.

**Comment by alexcroox** [comment]
For anyone looking for a server side solution, I'm currently using https://github.com/substack/point-in-polygon

**Comment by franckl** [comment]
Hi Alex, I use Mongo db for this task if you have lots of polygons or multi-polygons (see geoWithin / geoIntersect)
