### ISSUE TITLE
Use getBounds instead of everytime calculation

### ISSUE THREAD

**Issue by sectus** [mapbox/leaflet-pip#17]
Bounds of polygones already calculated. It's better to use it via getBounds to reduce calulcation time.

**Comment by tmcw** [comment]
Sounds good: could you create a PR implementing this change?

**Comment by tmcw** [comment]
Closing as idle. PRs are accepted that would complete this task but unfortunately I don't have enough time to implement it myself and it's unlikely I'll be able to implement it in the foreseeable future.

Sorry about that - if this feature is a must-have, happy to accept a Pull Request implementing it!
