### ISSUE TITLE
Example isn't working over HTTP on Chrome

### ISSUE THREAD

**Issue by JamesLMilner** [mapbox/leaflet-pip#21]
On Chrome you get the warning:

"getCurrentPosition() and watchPosition() are deprecated on insecure origins."

for the example of HTTP. You also get a lot of mixed content warnings over HTTPS: https://mapbox.github.io/leaflet-pip/

I think changing the description URL to HTTPS would be beneficial to people coming to the page. Happy to make the pull request if require.

**Comment by tmcw** [comment]
Thanks! We're now enforcing HTTPS and I switched the tile default to HTTPS to avoid the mixed content problem.
