### ISSUE TITLE
Uncaught TypeError: Cannot read property '1' of undefined

### ISSUE THREAD

**Issue by Craytor** [mapbox/leaflet-pip#23]
Hello! I'm trying to use this api library. I have my code looking like the following:
![](http://shots.tjyouschak.me/cTqeMt/Screen-Shot-2016-11-21-21-58-52.png)
![](http://shots.tjyouschak.me/L7XP2E/Screen-Shot-2016-11-21-22-00-04.png)

When I run this, and try to click on a polygon, all I get is this:
![](http://shots.tjyouschak.me/wk4CuV/Screen-Shot-2016-11-21-21-59-27.png)

I hope I explained this enough, I'm not sure what else to say other than I've been banging my head off my desk the past few days.

Please let me know if you need any more additional information.

**Comment by tmcw** [comment]
Okay, looking into it! Fix is happening in #24 which should resolve at least one of the issues with Leaflet v1

**Comment by tmcw** [comment]
Thanks, this _should_ be fixed in #24, which clears up some Leaflet v1 incompatibilities. Try out version 1.1.0: if it works, please close this issue. If it doesn't, please add a sample of the GeoJSON output from `http://weather_api.dev/alerts` so I can debug this further.

**Comment by Craytor** [comment]
Thanks, that was fast! So I went ahead and tried it, but I seem to be getting the same error (my fault possibly). I've went ahead and uploaded everything for testing purposes (I'll take it back down after we get this sorted out). The link of the app is [here](http://chasercast.com/app). Many thanks!

**Comment by tmcw** [comment]
Okay, tracked it down: there's a feature that looks like

```json
{
  "type": "Feature",
  "id": "4a1a777ddffb28ed6caabd67eabf49bef002bf82",
  "properties": {
    "fill": "#483D8B",
    "fill-opacity": 0.9,
    "stroke": "#000000",
    "stroke-width": 2,
    "stroke-opacity": 0.9,
    "headline": "Winter Weather Advisory issued November 20 at 5:18PM EST until November 21 at 4:00AM EST by NWS Pittsburgh",
    "description": "...WINTER WEATHER ADVISORY REMAINS IN EFFECT UNTIL 4 AM EST\nMONDAY...\n* STORM TOTAL ACCUMULATIONS...4 TO 6 INCHES...EXCEPT UP TO 10\nINCHES ON THE RIDGETOPS OF EASTERN TUCKER COUNTY.\n* PERIOD OF MOST INTENSE SNOW...THROUGH THIS EVENING.\n* SNOW ENDING...MONDAY LATE MORNING.\n* WINDS...WEST 15 TO 25 MPH WITH GUSTS UP TO 40 MPH.\n* IMPACTS...ROADS MAY BECOME SNOW COVERED AND SLIPPERY. IN\nCOMBINATION WITH THE WIND...BLOWING SNOW MAY REDUCE\nVISIBILITY... MAKING TRAVEL DIFFICULT."
  },
  "geometry": {
    "type": "MultiPolygon",
    "coordinates": [
      []
    ]
  }
}
```

While this is technically valid GeoJSON, it's a very rare variation, such that leaflet-pip's internal algorithm, [geojson-js-utils](https://github.com/maxogden/geojson-js-utils), is crashing on it. Omitting this feature (and any feature where the Polygon's coordinates look like `[[]]`, with no actual positions) should fix the issue.

So: I've [filed this issue upstream](https://github.com/maxogden/geojson-js-utils/issues/37), and if I can get co-maintainership of that module I can fix it there. In the meantime, omitting these features (that won't display on the map anyway) should be a fair workaround.

**Comment by Craytor** [comment]
@tmcw Alright, that did seem to be the issue. I went ahead and made my API so it doesn't return an alert if it doesn't have any coordinates for now. In the mean time I'll continue to watch your open issue with the upstream.

Finally, this could be a related issue(?), but when I click on some of the polygons, it is returning an empty array (and there is no pop up on the map), while others are working fine. For example, the (only) polygon in Nebraska works fine, but the polygon in the most northern part of California, and also the most southern part of California are not working at all. Does this make sense? The link to the project is the same, and is available [here](http://chasercast.com/app).

Do you want me to open a separate issue, or is here ok?

Again thanks for your help, I greatly appreciate it.
